language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=src/airduino.ino

install:
    - pip install -U platformio
    - platformio lib install 16 19 31 44 78 161 275

script:
    - platformio ci --lib="." --board=nanoatmega328
